# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_create_semaphore <- function(id, value = 0L) {
    invisible(.Call(`_semaphore_rcpp_create_semaphore`, id, value))
}

rcpp_sem_post <- function(id) {
    invisible(.Call(`_semaphore_rcpp_sem_post`, id))
}

rcpp_wait <- function(id) {
    .Call(`_semaphore_rcpp_wait`, id)
}

rcpp_try_wait <- function(id) {
    .Call(`_semaphore_rcpp_try_wait`, id)
}

rcpp_wait_seconds <- function(id, seconds = 0L) {
    .Call(`_semaphore_rcpp_wait_seconds`, id, seconds)
}

rcpp_wait_microseconds <- function(id, microseconds = 0L) {
    .Call(`_semaphore_rcpp_wait_microseconds`, id, microseconds)
}

rcpp_remove_semaphore <- function(id) {
    .Call(`_semaphore_rcpp_remove_semaphore`, id)
}

