# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_create_semaphore <- function(id, value = 0L) {
    invisible(.Call(`_semaphore_rcpp_create_semaphore`, id, value))
}

rcpp_increment_semaphore <- function(id) {
    invisible(.Call(`_semaphore_rcpp_increment_semaphore`, id))
}

rcpp_decrement_semaphore <- function(id, wait = TRUE, seconds = 0L) {
    .Call(`_semaphore_rcpp_decrement_semaphore`, id, wait, seconds)
}

rcpp_remove_semaphore <- function(id) {
    .Call(`_semaphore_rcpp_remove_semaphore`, id)
}

